In [1]:
import pickle
import numpy as np

In [2]:
## Code to load the array
with open('array.pickle', 'rb') as p:
    arr = pickle.load(p)
    
len(arr)   

1000

Check that the size of the array (arr) is 1000. Please report if any discrepancy.

## Task 1: Resize the array to a (20x50) matrix

In [3]:
## BEGIN CODE
arr_resized = np.resize(arr,(20,50))
arr_resized.shape
## END CODE

(20, 50)

## Task 2: Find the transpose of this matrix

In [4]:
## BEGIN CODE
arr_resized_trns = arr_resized.T
arr_resized_trns.shape
## END CODE

(50, 20)

## Task 3: Find the dot product of the matrices created in Tasks 1 & 2

In [5]:
## BEGIN CODE
DP = np.dot(arr_resized,arr_resized_trns)
DP.shape
## END CODE

(20, 20)

## Task 4: Find the row-wise sum of the resulting matrix

In [6]:
## BEGIN CODE
DP_RSum = DP.sum(axis=1)
DP_RSum
## END CODE

array([2365442.27809957, 3002112.3995789 , 2779184.43777157,
       2477210.32440039, 2627759.87742664, 2220803.79590608,
       2429710.18283941, 2508044.22721641, 2459318.36600334,
       2325031.07739166, 2896081.10050922, 2762062.07921721,
       2660473.74582437, 2141287.18395127, 2694809.41626161,
       2254508.32241154, 2480788.07237605, 2727792.51946167,
       2586794.20382212, 2681242.33967484])

## Task 5: Find the square root of all elements in the resulting matrix

In [26]:
## BEGIN CODE
DP_RSum_sqrt = np.sqrt(DP_RSum)
DP_RSum_sqrt
## END CODE

array([1537.99944021, 1732.66049749, 1667.08861125, 1573.91560269,
       1621.03666751, 1490.23615441, 1558.75276514, 1583.68059507,
       1568.2214021 , 1524.80525884, 1701.7876191 , 1661.94526962,
       1631.09587266, 1463.31376811, 1641.58746836, 1501.50202211,
       1575.05176816, 1651.60301509, 1608.35139314, 1637.44995028])

## Task 6: Find the sine value of all elements in the resulting matrix

In [27]:
## BEGIN CODE
Sine_values = np.sin(DP_RSum_sqrt)
Sine_values
## END CODE

array([-0.98203514, -0.99739839,  0.88988262,  0.0223149 , -0.02513909,
        0.90063852,  0.49931585,  0.31257026, -0.53682381, -0.90561256,
       -0.81665967, -0.04274285, -0.57228164, -0.61973772,  0.99446036,
       -0.17830768, -0.89740342, -0.76736444, -0.14354788, -0.62893124])

## Create submission file

In [28]:
## Assign the name of the variable containing the final matrix to VARIABLE_NAME variable.

VARIABLE_NAME = Sine_values
with open('submission.pickle', 'wb') as p:
    pickle.dump(VARIABLE_NAME, p)